### ISSUE TITLE
재귀트리 관련 질문 드립니다.

### ISSUE THREAD

**Issue by whateveriiwant** [JonghyeokPark/T03203302-2023#2]
안녕하세요, 교수님 자료구조 수강하고 있는 컴퓨터공학부 정승준입니다.
3주차 자료에서 39페이지의 재귀트리가 잘 이해가 안되어 질문 올립니다.

1. 트리 위에 써있는 점화식과 트리와의 관계를 잘 모르겠습니다. 
2. 처음의 부모노드인 n에서 자식노드인 n/2가 두 개 나오고 이후로도 계속 개수가 많아지는데 어떠한 방식에 의해 많아지는 건지 잘 이해가 안됩니다.
3. 각 레벨의 노드를 모두 더하면 항상 n이 나오는 건 이해가 되나 어떻게 그 비용들의 합계가 O(nlogn)이 나오는지 잘 이해가 안됩니다.

감사합니다.

**Comment by JonghyeokPark** [comment]
안녕하세요, 질문에 대한 답변을 하자면 다음과 같습니다.

트리와 트리위에 쓰여진 점화식의 관계를 생각하기에 앞서, 수업시간에 설명한 "Divde and Conquer" 개념을 한번 떠올려 봅시다. 

```
하나의 큰 문제 (problem) 를 작은 문제 (sub problem)으로 나눠서 해결하고, 각각의 subproblem의 합 (sum)을 구하면 problem의 solution을 구할 수 있다.
```

아래 식은 전체 문제, n에 대하여, (n/2)으로 나눈 subproblem들의 합을  점화식으로 표현한 것입니다.
2T(n/2)는 하나의 문제를 ***두개***의 부분문제로 나눈 것을 의미하고, 그 다음항인 n인 문제의 크기가 충분히 작아졌을 때 (입력의 크기가 충분히 작아졌을 때) 즉, 문제를 해결하는데 최소한의 시간을 나타냅니다.

```
T(n) = 2T(n/2) + n , T(1) = 1
```

트리를 보시면, 레벨이 증가될 때마다 (T(n)이 있는 레벨이 1레벨이라면, T(n/2) , T(n/2)이 있는 것은 레벨 2입니다.)
노드의 갯수가 2배씩 증가하는 것을 알 수 있습니다. (여기서 노드는  T(n), T(n/2)과 같이 간선(edge)로 연결되는 객체입니다.)
즉, 레벨 1에서는 노드 갯수는 1 (`2^(1-1)`)개 , 레벨 2에서는 노드 갯수는 2(`2^(2-1)`)개 , 레벨 3에서는 4(`2^(3-1)`)개 입니다.

각 노드의 값은 T(n/2) + n으로  계산됩니다.  이때 n/2의 값은 부분 문제의 크기입니다.
따라서, 아래 그림처럼, 부분 문제의 크기가 1이 될때까지 2로 나누는 작업을 반복하고 
그렇기 때문에 트리의 높이는 log_2(n)입니다.

```
       T(n)       
      /    \      
   T(n/2)  T(n/2)
    /  \     /  \
 T(n/4) T(n/4) T(n/4) T(n/4)
   .      .      .      .
   .      .      .      .
   .      .      .      .
 T(1)   T(1)   T(1)   T(1)
```

학생분 1,2 번 질문에 답변이 되었을것이라 생각이 됩니다.


3번 질문에 대한 답변을 하자면, 각 레벨에서의 합이 n인데, 위 답변에서 말해Temtdl, recursion tree의 높이는 log_2(n)입니다.
따라서, n * log_2(n)을 곱한 값이 전체 비용입니다.

**Comment by whateveriiwant** [comment]
감사합니다. 많은 도움이 되었습니다.
